version: '3.8'

services:
  hospital-app:
    # Instead of 'build: .', we will now specify the image name.
    # This tells Docker Compose to use the image you just manually built.
    image: hospital-managemnet-web-system3:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/hospitalSystem_db?useSSL=false&serverTimezone=UTC
      - DB_USER=root
      - DB_PASSWORD=
    depends_on:
      - db
    networks:
      - hospital-net

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: hospitalSystem_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - hospital-net
    ports:
      - "3306:3306"

networks:
  hospital-net:
    driver: bridge

volumes:
  db_data: